"""initial schema: weather_observations, crypto_prices, github_repo_stats, job_runs

Revision ID: 30e4061321b3
Revises: 
Create Date: 2026-08-08 15:11:52.702112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30e4061321b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_symbol', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_usd', sa.NUMERIC(), nullable=False),
    sa.Column('volume_24h', sa.NUMERIC(), nullable=True),
    sa.Column('market_cap', sa.NUMERIC(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_symbol', 'observed_at', name='uq_crypto_natural_key')
    )
    op.create_index('ix_crypto_prices_observed_at', 'crypto_prices', ['observed_at'], unique=False)
    op.create_table('github_repo_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo_full_name', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_full_name', 'observed_at', name='uq_github_natural_key')
    )
    op.create_index('ix_github_repo_stats_observed_at', 'github_repo_stats', ['observed_at'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_extracted', sa.Integer(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_source_started', 'job_runs', ['source_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.NUMERIC(), nullable=True),
    sa.Column('humidity_pct', sa.NUMERIC(), nullable=True),
    sa.Column('wind_speed_ms', sa.NUMERIC(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'observed_at', name='uq_weather_natural_key')
    )
    op.create_index('ix_weather_observations_observed_at', 'weather_observations', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weather_observations_observed_at', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('ix_job_runs_source_started', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_github_repo_stats_observed_at', table_name='github_repo_stats')
    op.drop_table('github_repo_stats')
    op.drop_index('ix_crypto_prices_observed_at', table_name='crypto_prices')
    op.drop_table('crypto_prices')
    # ### end Alembic commands ###
